## submit with:
## cmsenv;  condor_submit   -file submitFillHistograms.sub

executable  = $(cmssw)/src/UserCode/HGCElectronicsValidation/test/scripts/fillOccupancyHistograms.sh
arguments   = $(cmssw) $(samples_dir)/$(tag) $(maxevents) $(outdir) $(adcThrMIP) $(adcThrMIPbxm1)
output      = submitFillHistograms_condor.sub.out
error       = submitFillHistograms_condor.sub.err
log         = submitFillHistograms_condor.sub.log
+JobFlavour = "workday"

samples_dir   = /eos/cms/store/cmst3/group/hgcal/CMG_studies/Production

cmssw         = /afs/cern.ch/user/p/psilva/work/HGCal/CMSSW_11_2_0_pre1
#cmssw         = /afs/cern.ch/user/f/franzoni/work/CMSSW_11_2_0_pre1_bxm1/

maxevents     = -1
adcThrMIP     = 0.5
adcThrMIPbxm1 = 2.5

outdir        = /eos/cms/store/cmst3/user/psilva/HGCAL/EOL/
#outdir   =/eos/home-f/franzoni/www/CMS/HGCSample/SiOptim/2020-07-07-plots

queue tag from (      
      ttbar_D49_1120pre1_PU200_eolupdate_nopu_20200629
      ttbar_D49_1120pre1_PU200_eolupdate_nopu_nonoise_20200629
      ttbar_D49_1120pre1_PU200_eolupdate_no_OOT_20200701
      ttbar_D49_1120pre1_PU200_eolupdate_startup_20200629
      ttbar_D49_1120pre1_PU200_eolupdate_nopu_20200630
      ttbar_D49_1120pre1_PU200_eolupdate_noPerGainShape_20200701
      ttbar_D49_1120pre1_PU200_eolupdate_nopu_nonoise_20200630
      ttbar_D49_1120pre1_PU200_eolupdate_20200629
      ttbar_D49_1120pre1_PU200_eolupdate_20200630
      ttbar_D49_1120pre1_PU200_eolupdate_gf_20200629
      ttbar_D49_1120pre1_PU200_eolupdate_gf_20200630
      ttbar_D49_1120pre1_PU200_eolupdate_gf_20200705/
      ttbar_D49_1120pre1_PU200_eolupdate_nooot_nonoise_20200701
      ttbar_D49_1120pre1_PU200_eolupdate_startup_20200630
      ttbar_D49_1120pre1_PU200_eolupdate_4ab_800V_20200706
      #ttbar_D49_m20_1120pre1_PU200_eolupdate_20200701 ##these two need dedicated releases###
      #ttbar_D49_p20_1120pre1_PU200_eolupdate_20200702 ######################################
)
