
executable  = fillHistograms.sh 
arguments   = $(cmssw) /eos/cms/store/cmst3/group/hgcal/CMG_studies/Production/$(tag) $(maxevents) $(outdir)
output      = submitFillHistograms_condor.sub.out
error       = submitFillHistograms_condor.sub.err
log         = submitFillHistograms_condor.sub.log
+JobFlavour = "workday"

cmssw       = /afs/cern.ch/user/p/psilva/work/HGCal/Electronics/CMSSW_11_0_0_pre9/
maxevents   = -1
outdir      = /eos/cms/store/cmst3/user/psilva/HGCal/Occupancies

queue tag from (
      ttbar_ak8GenJetsNoNu_100_1_ttbar_v11_aged_biased_20191009
      ttbar_ttbar_v11_aged_unbiased_20191009
      FlatRandomPtGunProducer_NeutrinoGun_v11_aged_pu200_20191010
      FlatRandomPtGunProducer_NeutrinoGun_v11_aged_noOOT_20191010      
      FlatRandomPtGunProducer_NeutrinoGun_v11_aged_oldCode_20191010
      FlatRandomPtGunProducer_NeutrinoGun_v11_aged_noNoise_20191010
      FlatRandomPtGunProducer_NeutrinoGun_v11_aged_noOOT_noNoise_20191010
)